### ISSUE TITLE
g()是啥意思？

### ISSUE THREAD

**Issue by ShuGao0810** [noobiegz/cw2vec#5]
博主好，有个小问题，cw2vec_kernels.cc中关于g()的用法看不懂，也没有搜到相关用法，能否解释下g()是啥意思？谢谢！
`     

      // 1 / (1 + e^x) where x = sim(w, c) / k
      g = (1.f + ((Tqsum_acc * c).sum() / num_qs).exp()).inverse();

      Tq_update_acc = (lr * g() / num_qs) * c;

      // back prop into the true label
      c += (lr * g() / num_qs) * Tqsum_acc;
`

**Comment by qwfy** [comment]
算梯度用，梯度手工算一遍和代码对比下就可以了。
